name: Test
on:
  push:
  pull_request:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: tests
        with:
          path: node_modules
          key: ${{ runner.os }}-tests-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        if: steps.tests.outputs.cache-hit != 'true' # Over here!
        run: |
          npm i
      - name: Testing
        run: |
          npm run lint
          npm run test
