name: Deploy Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - "client/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: |
          cd server 
          cat <<EOT >>  app.yaml
          ${{ secrets.APP_YAML }} 
          EOT
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./server
