name: Build and Deploy Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - "client/**"
defaults:
  run:
    working-directory: ./server
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "347.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.project_id }}
          working_directory: /home/runner/work/MicrosoftEngageMentorship2021/server
