name: Build and Deploy Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - "client/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: cd server && echo ${{ secrets.APP_YAML }} > app.yaml && ls && cat app.yaml
#       - id: Deploy
#         uses: google-github-actions/deploy-appengine@main
#         with:
#           credentials: ${{ secrets.GCP_SA_KEY }}
#           working_directory: ./server
