name: Build and Deploy Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - "client/**"
defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_SA_KEY }}
    - uses: actions/gcloud/cli@master
      with:
        args: "app deploy --quiet --project=imersify"
