name: Build and Deploy Server
on:
  push:
    branches:
      - main
    paths-ignore:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./server
